
name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pytest-html
        cd src
        python -m pytest --html=pytest_report.html

    - name: Upload artefats
      uses: actions/upload-artifact@v3
      with:
        name: Report
        path: src/*.html

  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install pyinstaller
        cd src/test
        python -m PyInstaller "test_buscaHorario.py"

    - name: Upload artefats
      uses: actions/upload-artifact@v3
      with:
        name: Pacote
        path: src/test/dist/test_buscaHorario/test_buscaHorario.exe
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  notification:
      needs: [build, test]

      runs-on: ubuntu-latest
      env:
        EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}

      steps:
        - name: Executa scripts externos (à fim de enviar e-mail de congratulação)
          uses: actions/checkout@v4
        - run: sh scripts/shell.sh